Solid face renderer and related stuff.
zly2006/reden-is-what-we-made pull request #34
Opened 2023-09-15 02:09 UTC by lovexyn0827

### Description/描述

### Related Issues/相关的 issue

 

* fix #ISSUE_NUMBER
* resolve #ISSUE_NUMBER

### Checklist/清单

- [ ] The issues this PR addresses are related to each other/此 PR 解决的 issue 是相关的
- [ ] My changes are all related to the related issue above/我的修改都与上方的相关 issue 有关
- [ ] My changes generate no new warnings/我的修改没有产生新的警告
- [ ] My code builds and runs on my machine/我的代码在我的电脑上可以编译和运行
- [ ] I documented my code/我已经为我的代码添加了注释/文档

### Screenshots

## Added

- Carpet setting solidFaceRenderer
- Carpet setting solidFaceShapePredicate

2023-09-15 03:10 UTC, zly2006 commented
I think it is better to use a malilib config instead of carpet's.

2023-09-15 11:07 UTC, wafarm commented
MiniHUD has a feature `debugSolidFaceEnabled`, which highlight solid face with red color (screenshot below). What's the difference?
![image](https://github.com/zly2006/reden-is-what-we-made/assets/42467154/19b2b457-aa2a-4832-afdf-999b6184c852)

2023-09-15 11:40 UTC, lovexyn0827 commented
> MiniHUD has a feature `debugSolidFaceEnabled`, which highlight solid face with red color (screenshot below). What's the difference?
> ![image](https://github.com/zly2006/reden-is-what-we-made/assets/42467154/19b2b457-aa2a-4832-afdf-999b6184c852)
> 

MiniHUD的渲染器实际上使用的是原版中隐藏的BlockOutlineRenderer（yarn名），会将玩家坐标附近13*13*13的区域中所有方块的solid face都渲染到。

这里渲染器是只渲染玩家注视的方块对应的面，同时加入了对相应的面的形状判据的自定义功能（大致就是，可以通过配置使其渲染不完整的solid face）。

2023-09-15 12:57 UTC, zly2006 requested changes
consider using `ConfigOptionList` instead of just a string for predicate mode.

2023-09-15 13:01 UTC, lovexyn0827 commented
> consider using `ConfigOptionList` instead of just a string for predicate mode.

Should i introduce class `RedenOptionList` as it does not exist and other options uses `RedenConfigXXX` instead of classes in vanilla malilib.

2023-09-15 13:06 UTC, zly2006 commented
> Should i introduce class `RedenOptionList` as it does not exist and other options use `RedenConfigXXX` instead of classes in vanilla malilib.

Yes, that would be good.

2023-09-15 13:21 UTC, wafarm commented
> But the renderer here only renderers for the face targeted by the player. Besides, the customization of block face shape predication is supported (basically, it means non-full solid faces can be rendered.).

Got that. btw maybe you should place the code of config options according to their place in the UI, like below line 50.

2023-09-15 13:23 UTC, wafarm requested changes

2023-09-15 13:23 UTC, wafarm commented on src/main/java/com/github/zly2006/reden/malilib/MalilibSettings.kt
> +@JvmField val SOLID_FACE_SHAPE_PREDICATE = RedenConfigString("solidFaceShapePredicate", "full").generic()
I mean, move them up. (GitHub require comments on what need to be changed)

2023-09-15 13:36 UTC, Cubik65536 commented
Follow the PR template next time, otherwise I'll close it, IT IS THERE FOR A REASON.

2023-09-16 10:08 UTC, wafarm requested changes
Please remove unused import statements

2023-09-16 10:53 UTC, lovexyn0827 commented
> Please remove unused import statements

Done

2023-09-16 11:59 UTC, wafarm approved these changes

2023-09-16 17:44 UTC, zly2006 approved these changes

2023-09-16 22:17 UTC, Cubik65536 approved these changes

2023-09-17 02:52 UTC, merged