[WIP] refactor: Build a new tracking & versioning system
zly2006/reden-is-what-we-made pull request #7
Opened 2023-08-22 23:58 UTC by Cubik65536

This PR contains:

- [X] Deprecation of old tracking & versioning system codes
- [ ] Build a base architecture for new git-bases Minecraft structure tracking & versioning system
  - [ ] New data structure for block/entity/etc.
  - [ ] Serializer for the new data structure to plain text

2023-08-23 15:46 UTC, zly2006 commented
首先，实现一个RvcPlainIO和一个RvcGitIO，分别负责序列化到文本或托管于git，建议用组合而非继承，两者均实现一个RvcIO的接口

其次，PlainIO可以先写，git再说

2023-08-24 03:33 UTC, zly2006 requested changes

2023-08-24 03:33 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/io/RvcGitIO.kt
> +        // git pull action
这里只需要读取blob对象

2023-08-24 03:33 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/io/RvcGitIO.kt
> +        // git commit & push action
这里只要commit，不push

2023-08-24 03:33 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/io/RvcGitIO.kt
> +}
新增两个方法用于push和pull吧，以及来一个sync方法

pull可能有冲突，conflict resolver不会写可以先todo

2023-08-24 03:33 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/io/RvcIO.kt
> +class RvcIO(val rvcFileIO: RvcFileIO, val rvcGitIO: RvcGitIO) {
这个写成接口，看看有没有新方法可以加，如果和StructureIO没区别就删了

2023-08-24 22:42 UTC, Cubik65536 commented on src/main/java/com/github/zly2006/reden/rvc/io/RvcGitIO.kt
> +}
> 新增两个方法用于push和pull吧，以及来一个sync方法
> 
> pull可能有冲突，conflict resolver不会写可以先todo

`sync()` 用来干啥... 一个函数一起执行 `push()` 和 `pull()`

以及 `push()` 和 `pull()` 要不要什么参数

2023-08-24 23:16 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/io/RvcGitIO.kt
> +}
> 

可以接受一个remote branch参数？

我们毕竟要支持branch

2023-08-24 23:24 UTC, Cubik65536 commented on src/main/java/com/github/zly2006/reden/rvc/io/RvcGitIO.kt
> +}
> > 
> 
> 可以接受一个remote branch参数？
> 
> 我们毕竟要支持branch

Git 部分我先写成 [`5d3aea5` (#7)](https://github.com/zly2006/reden-is-what-we-made/pull/7/commits/5d3aea59026eb311dde906cef77e36db56a49586) 这样备注留空吧

2023-08-25 02:31 UTC, zly2006 requested changes

2023-08-25 02:31 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/io/RvcFileIO.kt
> +                    split[0],
不能这么写，Tick<T> where T: Block | Fluid, 这么写会造成值不相等甚至报错

2023-08-25 02:31 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/io/RvcFileIO.kt
> +                    split[0],
同

2023-08-25 23:35 UTC, zly2006 requested changes
全错！

nbt字符串可能有逗号，你这直接出错

请使用substring和indexof

2023-08-26 00:32 UTC, Cubik65536 commented
> @zly2006 
>
> 全错！
> 
> nbt字符串可能有逗号，你这直接出错
> 
> 请使用substring和indexof

处理了，有 conflict 你看看怎么弄下

2023-08-26 04:12 UTC, zly2006 commented
单独实现一个接口读取rvc文件，不同的版本使用不同的object来读取就好了

然后加上git就算可以merge了

2023-08-27 00:53 UTC, zly2006 commented
之前我的一个commit应该写了计划刻保存，你这样保存是错的，改一下吧

好怪，那个commit呢

2023-08-28 02:23 UTC, wafarm commented on src/main/java/com/github/zly2006/reden/utils/Utils.kt
> +    println("%2d".format(s) + unit[i])
Why formatting double with `%2d`?

2023-08-28 02:43 UTC, Cubik65536 commented on src/main/java/com/github/zly2006/reden/utils/Utils.kt
> +    println("%2d".format(s) + unit[i])
@zly2006 

btw why is this in this pr

2023-08-28 02:52 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/utils/Utils.kt
> +    println("%2d".format(s) + unit[i])
typo

2023-08-29 10:35 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/utils/Utils.kt
> +    println("%2d".format(s) + unit[i])
这个commit来自1.20主分支，已修复

2023-08-30 10:21 UTC, zly2006 approved these changes
looks great

2023-08-30 10:30 UTC, zly2006 commented
is this pr ready for review?

2023-08-30 11:13 UTC, Cubik65536 commented
@zly2006 Ready to merge!

I think it's better to do git operations in another PR, I'll sort out CI/CDs first.

2023-08-30 11:16 UTC, merged