doc: update translation of  Simple Chinese version of  readme
zly2006/reden-is-what-we-made pull request #77
Opened 2024-01-01 12:25 UTC by Matt-wzy

### Description/描述

更新 README.zh-CN.md，更新部分翻译以及添加部分新readme内容（有些实在是没看懂）

### Related Issues/相关的 issue

 

* fix NA
* resolve NA

### Checklist/清单

- [ ] The issues this PR addresses are related to each other/此 PR 解决的 issue 是相关的
- [ ] My changes are all related to the related issue above/我的修改都与上方的相关 issue 有关
- [x] My changes generate no new warnings/我的修改没有产生新的警告
- [ ] My code builds and runs on my machine/我的代码在我的电脑上可以编译和运行
- [ ] I documented my code/我已经为我的代码添加了注释/文档

### Screenshots

2024-01-01 14:12 UTC, zly2006 requested changes

2024-01-01 14:12 UTC, zly2006 commented on README.zh-CN.md
> +# Reden -- 在MC中的撤销(Ctrl +Z) 与重做(Ctrl+Y) 模组
请您先仔细看看介绍，谁说这个模组的功能**主要是**undo了？

2024-01-01 18:55 UTC, Cubik65536 requested changes

2024-01-01 18:55 UTC, Cubik65536 commented on README.zh-CN.md
> +快捷键 (malilib -> General)	默认
需要与英文 README 同步，使用表格

2024-01-01 18:55 UTC, Cubik65536 commented on README.zh-CN.md
> +Ctrl+Z  撤销 ，妈妈再也不怕我炸珍珠炮啦！Ctrl+Y 重做（取消撤销），爸爸再也不怕我把世界撤销到初始状态啦！
```suggestion
Ctrl+Z 撤销 ，妈妈再也不怕我炸珍珠炮啦！Ctrl+Y 重做（取消撤销），爸爸再也不怕我把世界撤销到初始状态啦！
```

另外，我认为最好遵循英文原文内容（待讨论）

2024-01-01 18:55 UTC, Cubik65536 commented on README.zh-CN.md
>  更多信息请参阅[wiki页面](https://wiki.redenmc.com/Undo-and-Redo)
```suggestion
更多信息请参阅 [wiki页面](https://wiki.redenmc.com/Undo-and-Redo)
```

Markdown 格式要求，以后会在单独的文档中写明，目前直接更改

2024-01-01 18:55 UTC, Cubik65536 commented on README.zh-CN.md
> +红石版本控制 RVC( Redstone Version Control)，管理机器的修改历史、分析历史记录。
``` suggestion
红石版本控制 RVC (Redstone Version Control)，管理机器的修改历史、分析历史记录。
```

Markdown 格式问题，上面那个可以是项目标准没公布，这个错的离谱了

2024-01-02 12:25 UTC, Matt-wzy commented on README.zh-CN.md
> +快捷键 (malilib -> General)	默认
此处是一个低级失误，已在最新的提交中修正

2024-01-02 12:27 UTC, Matt-wzy commented on README.zh-CN.md
> +Ctrl+Z  撤销 ，妈妈再也不怕我炸珍珠炮啦！Ctrl+Y 重做（取消撤销），爸爸再也不怕我把世界撤销到初始状态啦！
已开启 Allow edits by maintainers 讨论完毕后可以直接修改此处，暂时保留

2024-01-02 12:28 UTC, Matt-wzy commented on README.zh-CN.md
>  更多信息请参阅[wiki页面](https://wiki.redenmc.com/Undo-and-Redo)
已在最新的提交中修正

2024-01-02 12:28 UTC, Matt-wzy commented on README.zh-CN.md
> +红石版本控制 RVC( Redstone Version Control)，管理机器的修改历史、分析历史记录。
已在最新的提交中修正

2024-01-02 18:21 UTC, Cubik65536 requested changes

2024-01-02 18:21 UTC, Cubik65536 commented on README.zh-CN.md
> +Ctrl+Z 撤销 ，妈妈再也不怕我炸珍珠炮啦！Ctrl+Y 重做（取消撤销），爸爸再也不怕我把世界撤销到初始状态啦！
请尊重原文

2024-01-03 17:47 UTC, Cubik65536 commented
把之前改对的格式化改回去了真是无语了

2024-01-03 17:47 UTC, Cubik65536 approved these changes

2024-01-03 17:48 UTC, merged