feat: rvc import gui (gui only)
zly2006/reden-is-what-we-made pull request #86
Opened 2024-01-22 22:17 UTC by iMoonDay

### Description/描述

实现Import GUI，但未完善具体Import功能

添加2个按键对应Import GUI (R+I)和Export GUI (R+E)

### Checklist/清单

- [ ] The issues this PR addresses are related to each other/此 PR 解决的 issue 是相关的
- [ ] My changes are all related to the related issue above/我的修改都与上方的相关 issue 有关
- [x] My changes generate no new warnings/我的修改没有产生新的警告
- [x] My code builds and runs on my machine/我的代码在我的电脑上可以编译和运行
- [ ] I documented my code/我已经为我的代码添加了注释/文档

### Screenshots
![image](https://github.com/zly2006/reden-is-what-we-made/assets/124775693/6054cf31-cde2-4965-8179-f3d537b685fc)

2024-01-22 23:06 UTC, Cubik65536 commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +                    .forEach { rootComponent.child(screen.FileLine(it)) }
Why here's also Litematica related operations?

2024-01-22 23:09 UTC, iMoonDay commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +                    .forEach { rootComponent.child(screen.FileLine(it)) }
这部分是 @zly2006 修改的，并非我的源代码，我也不清楚

2024-01-22 23:11 UTC, iMoonDay commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +                    .forEach { rootComponent.child(screen.FileLine(it)) }
This part was modified by @zly2006 and is not my source code, so I don’t know

2024-01-22 23:12 UTC, Cubik65536 commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +                    .forEach { rootComponent.child(screen.FileLine(it)) }
> This part was modified by @zly2006 and is not my source code, so I don’t know

https://github.com/zly2006/reden-is-what-we-made/pull/86/commits/21620cc7e17e83899ee2e7fc9895318d3835f636#diff-cf4acc03943058b07d58a08062a131e3775a55be73eead4566f96f823fe6de86R195-R206

But it is from your commit.

2024-01-22 23:13 UTC, iMoonDay commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +                    .forEach { rootComponent.child(screen.FileLine(it)) }
I once submitted a PR, but it was lost. This PR is the final code after all previous modifications.

2024-01-22 23:13 UTC, Cubik65536 commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +                    .forEach { rootComponent.child(screen.FileLine(it)) }
> I once submitted a PR, but it was lost. This PR is the final code after all previous modifications.

Ok then

2024-01-22 23:21 UTC, iMoonDay commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +                    .forEach { rootComponent.child(screen.FileLine(it)) }
This part was modified in this branch: [fix: gui bugs, changed hotkey config order](https://github.com/zly2006/reden-is-what-we-made/pull/86/commits/52a96965bc138eaff17941c53289f94fb2bd458b)

2024-01-22 23:35 UTC, Cubik65536 approved these changes
LGTM

2024-01-22 23:35 UTC, Cubik65536 commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +                    .forEach { rootComponent.child(screen.FileLine(it)) }
OK I get it then

2024-01-23 00:13 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +                    .forEach { rootComponent.child(screen.FileLine(it)) }
The category "Other" refers to some schematic files that are not litematica's, usually created by worldedit or some other tools. They are in a similar format to structure block.

2024-01-23 00:17 UTC, zly2006 commented
The last commit:
1. added `name` field.
2. Improved structure block file display, e.g. `namespace:a` now is shown as `namespace:a` not `a` (namespace `minecraft` is still ignored by default)
3. **removed useless tooltips**, do we still need that?

2024-01-23 08:41 UTC, zly2006 requested changes
再考虑到一个全新的需求： #87，你必须添加另一个分类实现读取.rvcarchive文件，此文件也在schematics目录下，简单实现一下吧

2024-01-23 08:41 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +        vararg tooltips: Text,
tooltips已经不再需要

2024-01-23 08:41 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/rvc/gui/SelectionImportScreen.kt
> +    enum class Type(val displayName: String) {
显示相关的文本都要用Text表示，再仔细检查一下你的代码please

2024-01-23 14:47 UTC, zly2006 approved these changes

2024-01-23 14:51 UTC, merged