feat: Require confirmation when opening survival saves.
zly2006/reden-is-what-we-made pull request #95
Opened 2024-02-11 18:57 UTC by lovexyn0827

### Description/描述

添加了一个在尝试打开生存存档时显示的确认界面，以防止玩家意外地打开生存存档。

Added a confirmation screen displayed when attempting to open survival save, to prevent survival saves from being opened accidentally.

### Related Issues/相关的 issue

 

无

None

### Checklist/清单

- [N/A] The issues this PR addresses are related to each other/此 PR 解决的 issue 是相关的
- [N/A ] My changes are all related to the related issue above/我的修改都与上方的相关 issue 有关
- [x] My changes generate no new warnings/我的修改没有产生新的警告
- [x] My code builds and runs on my machine/我的代码在我的电脑上可以编译和运行
- [x] I documented my code/我已经为我的代码添加了注释/文档

### Screenshots

![2024-02-12_02 42 53_2](https://github.com/zly2006/reden-is-what-we-made/assets/34397094/9abee406-d80b-4c18-9ec4-81879d85f779)
![2024-02-12_02 57 11](https://github.com/zly2006/reden-is-what-we-made/assets/34397094/1d412621-5020-4a73-91d7-d6370630df5c)

2024-02-17 08:58 UTC, zly2006 commented
啊，下次如果写好了记得request一下review，我没收到邮件都不知道你写了这个😂

2024-02-17 09:05 UTC, zly2006 requested changes

2024-02-17 09:05 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/mixin/survivalProtection/MixinWorldListWidgetEntry.java
> +            BooleanConsumer bc = (bool) -> {
why?

用户没点确定时，直接cancel就是了嘛，写的多此一举

2024-02-17 09:05 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/mixin/survivalProtection/IMixinWorldListWidget.java
> +    @Invoker("load")
同上，多此一举，这个mixin可以删了

2024-02-17 09:09 UTC, zly2006 commented
还有一点我比较在意，关于这个PR是否真的需要。

+ 部分功能需要carpet开启，但是carpet命令本身就需要作弊了
+ reden自己有判断创造的检查，包括undo等，我的建议是找出问题，并通过Hello packet、权限检查等方式解决，而不是粗暴的不让用户进存档。同时这种页面最好留下never show again和help链接（一般可以在wiki写help页面）

2024-02-17 09:28 UTC, lovexyn0827 commented on src/main/java/com/github/zly2006/reden/mixin/survivalProtection/MixinWorldListWidgetEntry.java
> +            BooleanConsumer bc = (bool) -> {
在用户准备打开生存存档的时候客户端会显示一个界面来让玩家确认，如果玩家没有选择确定这里需要再将界面切换到存档列表界面下，不进行操作的客户端会卡在确认界面下。另外这个Callback是丢给ConfirmScreen来响应用户操作的，直接cancel()会无法生效。

如果是指只在玩家取消操作时cancel掉打开存档的操作的话，就需要在打开存档的那个方法里阻塞住客户端线程来等来用户确认，但是MC的原版机制不支持这么做。

（这个方法只负责显示界面与取消加载存档的操作，用户操作的处理是由里面的Lambda处理的）

2024-02-17 09:38 UTC, lovexyn0827 commented
> 还有一点我比较在意，关于这个PR是否真的需要。
> 
> * 部分功能需要carpet开启，但是carpet命令本身就需要作弊了
> * reden自己有判断创造的检查，包括undo等，我的建议是找出问题，并通过Hello packet、权限检查等方式解决，而不是粗暴的不让用户进存档。同时这种页面最好留下never show again和help链接（一般可以在wiki写help页面）

也不是很确定，但是打开生存存档这一操作不在模组的设计范围内，本身也不太被推荐，提醒一下用户并防止误操作还是有一定需要的。（自己的MessMod甚至曾经有一段时间会默认隐藏生存存档）

never show again的话当时考虑过用Reden在存档中生成的特征性文件作为依据，但是考虑到文件以后有可能发生变更还有用户可能需要进行特殊配置就没有这么做。（不知道单独写一个配置存储会不会有些多余）

2024-02-17 10:36 UTC, zly2006 commented
> 也不是很确定，但是打开生存存档这一操作不在模组的设计范围内，本身也不太被推荐，提醒一下用户并防止误操作还是有一定需要的。（自己的MessMod甚至曾经有一段时间会默认隐藏生存存档）

但是你要考虑到因为一个模组就单独配一个客户端……不太现实，这可能导致用户不喜欢用你的东西

> never show again的话当时考虑过用Reden在存档中生成的特征性文件作为依据，但是考虑到文件以后有可能发生变更还有用户可能需要进行特殊配置就没有这么做。（不知道单独写一个配置存储会不会有些多余）

有一个简陋的实现在`com.github.zly2006.reden.gui.message.ClientMessageQueue#dontShowAgain`，可以标记某一个key对应的信息不要展示，禁用这个警告做成全局的即可

2024-02-17 14:07 UTC, lovexyn0827 commented
> 但是你要考虑到因为一个模组就单独配一个客户端……不太现实，这可能导致用户不喜欢用你的东西

也确实有这一方面的问题，毕竟还是要兼顾用户操作的便捷性的。

但是也会有原版主义者不希望在加载专适用于创造模式的模组时打开生存存档，并且认为这种操作会破坏生存存档的纯粹性。~实际上，自己还真的专门为各种用途分了好几个个客户端，因为在很多启动器配置后版本隔离的开销也不算太大。~

考虑到用户的偏好不同，不知道用Malilib给这一特性做一个默认启用的Rule是否合适。

2024-02-17 14:28 UTC, zly2006 commented
> 但是也会有原版主义者不希望在加载专适用于创造模式的模组时打开生存存档，并且认为这种操作会破坏生存存档的纯粹性。~实际上，自己还真的专门为各种用途分了好几个个客户端，因为在很多启动器配置后版本隔离的开销也不算太大。~
> 
> 考虑到用户的偏好不同，不知道用Malilib给这一特性做一个默认启用的Rule是否合适。

同意，同时**建议**当用户进入本地生存档后使用`com.github.zly2006.reden.gui.message.ClientMessageQueue`向他们提醒潜在的not vanilla风险，并**建议**在wiki编写有关帮助

2024-02-18 06:51 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/mixin/survivalProtection/MixinWorldListWidgetEntry.java
> +            BooleanConsumer bc = (bool) -> {
哦那确实，但是：

- lambda不要单独弄出来一个变量
- 除非模组冲突，建议使用access widener而非mixin

2024-02-18 06:51 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/mixin/survivalProtection/MixinWorldListWidgetEntry.java
> +            default -> "https://wiki.redenmc.com/index.php/Survival_Save_Protection";
reden wiki的url没有index.php，而且有i18n插件你不用写这么多链接

2024-02-18 08:19 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/mixin/survivalProtection/MixinWorldListWidgetEntry.java
> +                        if(bool) {
`bool` -> `confirmed`

2024-02-18 08:19 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/mixin/survivalProtection/MixinWorldListWidgetEntry.java
> +        String url = Text.translatable("reden.widget.survival.link").getString();
你是不是理解错了？wiki有i18n插件不需要模组来实现

强烈建议你先去把wiki写了，不然可能都不知道我在说啥

2024-02-18 08:28 UTC, lovexyn0827 commented on src/main/java/com/github/zly2006/reden/mixin/survivalProtection/MixinWorldListWidgetEntry.java
> +        String url = Text.translatable("reden.widget.survival.link").getString();
OK

2024-02-18 11:57 UTC, lovexyn0827 commented
（已经几乎被Wiki翻译单元标记折磨到要放弃了）

2024-07-15 10:22 UTC, closed without merging