New language and new translation.
zly2006/reden-is-what-we-made pull request #99
Opened 2024-03-16 06:48 UTC by is52hertz

### Description/描述

### Related Issues/相关的 issue

 

* fix #ISSUE_NUMBER
* resolve #ISSUE_NUMBER

### Checklist/清单

- [ ] The issues this PR addresses are related to each other/此 PR 解决的 issue 是相关的
- [ ] My changes are all related to the related issue above/我的修改都与上方的相关 issue 有关
- [ ] My changes generate no new warnings/我的修改没有产生新的警告
- [ ] My code builds and runs on my machine/我的代码在我的电脑上可以编译和运行
- [ ] I documented my code/我已经为我的代码添加了注释/文档

### Screenshots

2024-03-16 06:51 UTC, zly2006 requested changes

2024-03-16 06:51 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/carpet/RedenCarpetSettings.java
> +                        source.sendMessage(Text.translatable("reden.Carpet.warning" + ": ").formatted(Formatting.RED)
translation key必须小写

2024-03-16 06:51 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/carpet/RedenCarpetSettings.java
> +                        source.sendMessage(Text.translatable("reden.Carpet.warning" + ": ").formatted(Formatting.RED)
同时，此处应该使用rich translation（see：https://docs.wispforest.io/owo/rich-translations/）

2024-03-16 06:55 UTC, is52hertz commented on src/main/java/com/github/zly2006/reden/carpet/RedenCarpetSettings.java
> +                        source.sendMessage(Text.translatable("reden.Carpet.warning" + ": ").formatted(Formatting.RED)
.formatted(Formatting.RED)
这个?

2024-03-16 06:57 UTC, is52hertz commented on src/main/java/com/github/zly2006/reden/carpet/RedenCarpetSettings.java
> +                        source.sendMessage(Text.translatable("reden.Carpet.warning" + ": ").formatted(Formatting.RED)
{ "text": "警告", "color": "red"}
这样吗?

2024-03-16 06:58 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/carpet/RedenCarpetSettings.java
> +                        source.sendMessage(Text.translatable("reden.Carpet.warning" + ": ").formatted(Formatting.RED)
> { "text": "警告", "color": "red"} 这样吗?

是的，请修改

2024-03-16 07:16 UTC, zly2006 requested changes

2024-03-16 07:16 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/carpet/RedenCarpetSettings.java
> +                                .append(Text.translatable("reden.carpet.redendebuggerenabled").styled(style ->
小写不是让你连在一起，下划线。

2024-03-16 07:16 UTC, zly2006 commented on src/main/resources/assets/reden/lang/zh_tw.yml
> +    warning: { "text": "警告", "color": "red"}
再好好看看rich trnaslation格式，本项目中有示例

2024-03-16 07:16 UTC, zly2006 commented on src/main/java/com/github/zly2006/reden/carpet/RedenCarpetSettings.java
> +                                .append(Text.translatable("reden.carpet.redendebuggerenabled").styled(style ->
redenDebuggerEnabled应该用%s方式传入

2024-03-16 08:01 UTC, zly2006 commented
Link to #29

2024-03-16 14:47 UTC, zly2006 commented
why ready for review? There are no more commits updated.

2024-03-17 02:38 UTC, is52hertz commented
> why ready for review? There are no more commits updated.

I'm going to go ahead and submit it first and create a new PR for a later one, because I'm working on other things right now and can't be bothered to do that.

2024-03-21 16:46 UTC, zly2006 commented
rich i18n底层代码已更新，see：https://github.com/zly2006/reden-is-what-we-made/blob/ee1ac3c27051e102b50bb0ed01ad9d107d938d38/src/main/java/com/github/zly2006/reden/utils/richTranslation/RichTranslation.kt

2024-07-15 10:22 UTC, closed without merging